# Generated by Django 4.0.4 on 2024-06-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='sensor',
            field=models.BooleanField(default=False),
        ),
    ]
