# Generated by Django 4.0.4 on 2022-04-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('daily', 'Daily'), ('six', 'Six'), ('hourly', 'Hourly')], default='daily', max_length=10),
        ),
    ]
